admin_password = "admin123"

[google]
type = "service_account"
project_id = "cirqit-dashboard"
private_key_id = "79187b6c6d1473bb63094fa90c9a807d67b9af1b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDBjy8AXsv2Kefo
2+9epW/mkaR2RN2W2JBZ7CsUeAz7grul11K5vd6noqLupuxIP8wIlwq9oZFBjJmq
BPino+F+Sq7TasacyBvbQ3TDMCkkPIw3ecbsEKciv2bSg78uTjPn+jLaPmkR8B9B
yq8dumW3Cu1Uq5voEOu0L+Xyj6YtN1nS6oEGRWobjOqQKpmuq3KWEWD/r9YP51lz
/Ge63+HGKQA0ynRu9hgK5bd9fX0TB7S5/hx+b4RzbNx++OEncWQJj8aN+FJ7eF1x
O/3XcrKtcwr6t/9yHEbg0VDyyOx4LnayfzX6PfBEuRtu44vj8+f3W6y5MpnK3ANw
LDb1jk1tAgMBAAECgf8Nr1689MOqI+X03Zf1ZfA2qeJDrZrJ9ew+1cCcZRO5GwUp
Z8MkxS5Fq+0/i/QowSbFdLU0GYUSA8U/800683TkX2NjXA+u0t2LvLk34HyhxnLw
Rfiw60lMRTwZcwP3wilPvXp0jVt6Asz/wDs6+HLSMXOWPCV89hu0Ia7TkSFIRDVN
IGdQi/iW0VPKBb3Osy7m+lHWr416ZnUMMfyRIC4HGIRkzkWwO0jYVQBTJ61M1NY4
xJATFqNWhy57XS+gtxWovkJxcRUk2aWdo4h4xcSzb1tZy3XQL+nh/6L/Izl+Y+eB
kVSE6H5JprxPe8RatOB2yD0C4KA0OEbQe2RA3cECgYEA4visTJyk8FkapRuGpfpj
qpYLnHPL2iBldESj48ic5rTYDQdXsowp8Yo05OIIIuzIe7y6bo6BMFRnOCZ5rrgL
CQ3OAXIXQXkdX4aSUEVao7d+CNJQy3/mBoVEgV1tK44hbKxYMdddr//ysHo8rKL5
Vxr2kMjzx9iWFHeKP7Ufe6ECgYEA2lCOwUQkNsbZSZof+8Sq61QFdRwUMjE8F2zV
6ObF2zIxMvjK7dBbYjyRDTTUFuURcM/wc1lIq3Ae0uELrC+8dM4anEke70Rd8xVL
o4VI/l0oheUyt15ysIRk7sRlWqMfdCcUHcfQhDdqJ5tHA34roNXnMqlN2rH7Pxsp
qPYRXk0CgYB8qrQQ3JVoArk06RqbPh3SS9oS1DOrGtI++5i9e6paughVl6vewUgk
iJInCdQIQuCXvoD0SsfA4QtU9yUtB5/gGDoH5z/I0ZqFpqfk+UMg25+ZftOsAxM4
j6iiGcvl+Yp4Y22J6s5l5oLJ1kpPVLD53DCENCxan6dHlKVV+slRIQKBgD0u/IMf
lMKhQf5FqpcFzBz9xDXI88QJVlz+TIjkPCktTOqLHVw+242RidlYp+PuuM+UB0Bc
kmgxmQHivkG4cymNJZoNSBUoZOgeXL9sOEPJWfUEgg0v9BaSVDMyaXFYbBVCanna
KQ8U9LQ66VEKSDHgINZq6n3TCaXq9+b5Z261AoGAWsJLwomXytMU5kN96JThrlPk
WASvSsFZLSZT9NpdOfjS7gLJMCrSXf8bRnOI3C+soILoRNUQuZHF0ITQixWaEJEC
QbxZ/zV3q6sUTiNnkLzE7p6yOQDg/NilKPzTWtrbh2akek0txtfNjsz0NlTtX+FF
qAVMgHaruTU6ZR5neR4=
-----END PRIVATE KEY-----"""
client_email = "circuit-dashboard-bot@cirqit-dashboard.iam.gserviceaccount.com"
client_id = "106126655242503798280"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/circuit-dashboard-bot%40cirqit-dashboard.iam.gserviceaccount.com"
universe_domain = "googleapis.com"